package com.medilab.microservice_backend_note.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * The note model store the note wrote by the medical staff.
 * Stored in the table note.
 * <p>
 * Id attribute is a random UUID automatically generated by the constructor and parsed in a String format.
 * Patient attribute is the Patient's id who is handled by the microservice-backend-patient.
 * CreatedAt attribute is a LocalDateTime automatically generated by the constructor.
 * </p>
 */
@Document(collection = "notes")
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class Note {
    
    @Id
    private String id;
    private String patient;
    private String note;
    private LocalDateTime createdAt;
    
    public Note(String patient, String note) {
        this.id = UUID.randomUUID()
                .toString();
        this.patient = patient;
        this.note = note;
        this.createdAt = LocalDateTime.now();
    }
}
