version: '3.3'

services:

  configuration-server:
    container_name: configuration-server
#    healthcheck:
#      test: curl --fail http://configuration-server:9101 || exit 1
#      interval: 3s
#      timeout: 30s
#      retries: 3
    build:
      context: configuration_server
      dockerfile: Dockerfile
    restart: always
    expose:
      - 9101
    ports:
      - "9101:9101"

  microservice-back-mysql:
    container_name: microservice-back-mysql
    image: mysql:8.0
#    healthcheck:
#      test: curl --fail http://microservice-back-mysql:9090 || exit 1
#      interval: 3s
#      timeout: 30s
#      retries: 3
    restart: always
    expose:
      - 9090
    ports:
      - "9090:9090"
    environment:
      MYSQL_DATABASE: medilabo_solutions
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_TCP_PORT: 9090

  eureka-server:
    container_name: eureka-server
#    healthcheck:
#       test: curl --fail http://eureka-server:9102/ || exit 1
#       interval: 3s
#       timeout: 30s
#       retries: 3
    depends_on:
#      configuration-server:
#        condition: service_healthy
      - configuration-server
    build:
      context: eureka_server
      dockerfile: Dockerfile
    restart: always
    expose:
      - 9102
    ports:
      - "9102:9102"
    environment:
      spring.cloud.config.uri: http://configuration-server:9101
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka:password@localhost:9102/eureka

  microservice-back:
    container_name: microservice-back
    depends_on:
#      configuration-server:
#        condition: service_healthy
#      microservice-back-mysql:
#        condition: service_healthy
#      eureka-server:
#        condition: service_healthy
      - configuration-server
      - microservice-back-mysql
      - eureka-server
    build:
      context: microservice_back
      dockerfile: Dockerfile
    restart: always
    expose:
      - 9001
    ports:
      - "9001:9001"
    environment:
      spring.cloud.config.uri: http://configuration-server:9101
      eureka.client.serviceUrl.defaultZone: http://eureka:password@eureka-server:9102/eureka
      spring.datasource.url: jdbc:mysql://microservice-back-mysql:9090/medilabo_solutions?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true&serverTimezone=UTC
      spring.datasource.username: root
      spring.datasource.password: rootroot
      spring.datasource.root.password: rootroot
      spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect


